# -*- coding: utf-8 -*-
"""Numpy _Class4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDP8_qSQMdi6jwsjTf2AHzvX8giBDV5J
"""

import numpy as np

a=np.random.rand(5)
print(a.ndim)

a=np.random.rand(2,3)
print(a)

a=np.random.rand(3,2,2)
print(a)

a=np.random.randint(1,10,5)
print(a)

a=np.random.randint(1,11,(2,5))
print(a)

a=np.random.randint(1,10,(2,3,5))
print(a)

a=np.random.randn(5,2,7)
print(a)

a=np.array([1,10])
b=np.random.choice(a,(2,3))
print(b)

a=np.array([1,3,10])
b=np.random.choice(a,(2,9,9))
print(b)

a=np.array([1,2,3,4,5,6,7,8,8])
print(a.ndim)
print(a[3])
print(a[6])

"""Accessing Elements in 2 Array

"""

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a.ndim)
print(a)
print(a[0,2])
print(a[1,1])
print(a[-3,-2])

"""Accessing Elements in 3 d Array"""

a=np.arange(0,18).reshape(2,3,3)
print(a)
print(a[0,2,2])
print(a[0,2,0])
print(a[1,2,0])
print(a[-2,0-2])

