# -*- coding: utf-8 -*-
"""Numpy_practice - 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2CS8iQy8jnGHlw8Y-rfbaPowgawSO4d
"""

pip install numpy

l=[1,2,3,4,4]
print(type(1))

import numpy as np
l=[1,2,3,4,4,'numpy']
a=np.array(l)
print(a)
print(type(a))
print(a.dtype)

l=[1,2,3,4,'Numpy',5.0]
# print(l[0])
for i in l:
  print(type(i))

import numpy as np
a=np.array([1,2,3,4,'numpy',5.0])
for i in a:
  print(type(i))

import numpy as np
a=np.array([[1,2],[1,9]])
print(a.ndim)

import numpy as np
a=np.array([[[1,2,3],[4,5,6],[45,7,99]]])
print(a)
print(a.ndim)

import math
import numpy as np
import time

a=7
b=np.array(7)
start=time.time()
print(math.sqrt(a))
end=time.time()
print("math",end-start)
start=time.time()
print(np.sqrt(b))
end=time.time()
print("Numpy",end-start)

