# -*- coding: utf-8 -*-
"""Numpy_Class2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5pVwj-JOfYRWoyIZMkp6bxxfkq8xytL
"""

l=[1,2,3,4,5]
print(type(l))

import numpy as np
L=[1,2,3,4,5]
print(type(L))
print(l)
a=np.array(L)
print(type(a))
print(a)

import numpy as np
l=[[2,3,6,7,8,'numpy']]   #2 D Array
a=np.array(l)
print(a)
print(a.shape)  # row and Colums
print(a.size)  # no. of Elements
print(a.dtype)  #datatype
print(a.ndim)  #dimension
print(a.itemsize)  #Each Element Size
print(a.nbytes)   # Total Array Size

import numpy as np
a=[[1,2,3],[1,2,3]]
a=np.array(a)
print(a)
print(a.ndim)
print(a.shape)
print(a.itemsize)
print(a.nbytes)
print(a.dtype)

l=[[[1,2,3]],[[1,2,3]]]
a=np.array(l)
print(a)
print(a.shape)

t=((1,2,3),(4,5,6))
a=np.array(t)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.nbytes)
print(a.dtype)

l=[[1,2,3]]
t=((1,2,3),(4,5,6))
a=np.array(l)
print(a.ndim)
b=np.array([[t]])
print(b.ndim)

