# -*- coding: utf-8 -*-
"""Numpy_Class - 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EN_BVKrDokSUXp7k7jJKEI6ou6evVpul
"""

import numpy as np
a=np.arange(0,10,1)
print(a)

a=np.arange(1,10,3)
print(a)
print(type(a))

a=np.arange(10,100)
print(a)

a=np.arange(10)
print(a)

a=np.linspace(1,10,4)
print(a)

a=np.arange(1,10,4)
print(a)

a=np.linspace(1,10,11)
print(a)

a=np.zeros(2)
print(a)

a=np.zeros([2,3,4])
print(a)

a=np.ones(2)
print(a)

a=np.ones([3,5,4])
print(a)

a=np.linspace(2,3,5)
print(a)

a=np.eye(3)
print(a)

a=np.identity(3)  # must should be a square matrix i.e. row=column
print(a)

a=np.eye(3,2)
print(a)
print("=========")
a=np.eye(3)
print(a)
print("==========")
a=np.eye(2,3)
print(a)

a=np.arange(0,9).reshape(3,3)
print(a)
print(a.ndim)
print(a.shape)

a=np.arange(0,4).reshape(2,2)
print(a)
print(a.ndim)
print(a.shape)

a=np.arange(0,18).reshape(2,3,3 )
print(a)
print(a.ndim)
print(a.shape)

a=np.linspace(1,10,18).reshape(2,3,3)
print(a)
print(a.ndim)
print(a.shape)

a=np.array([[1,2,3],[4,5,6]]).reshape(3,2)
print(a)
print(a.ndim)
print(a.shape)

a=np.array([[1,2,3],[4,5,6]])
print(a)
print("===================")
print(a.reshape(6,))

a=np.array([1,2,3])
a=np.tile(a,(2,3,4))
print(a)
print("================")
print(a.flatten())     #  changes to 1-Dimensional

a=np.array([1,2,3,4])
print(a)
print(a.dtype)
print(a.astype(float))
print(a.astype(str))

a=np.array([1,2,3,4],dtype=str)
print(a)

